version: '3.3'
services:
  apiservice:
    build: ./apiservice
    ports:
     - "3000:3000"
    expose:
     - '3000'
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
     - DATABASE_DATABSE=ase
     - DATABASE_USER=harry
     - DATABASE_PASSWORD=password
    volumes:
     - ./apiservice/api/public/images:/opt/images
     - ./apiservice/api:/app/api
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ase'
      MYSQL_USER: 'harry'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ase-db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
volumes:
  ase-db:
